# Generated by Django 2.1.3 on 2018-12-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20181210_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profil_picture',
            field=models.ImageField(default='static/images/ecran.png', upload_to='static/images/'),
        ),
    ]
