# Generated by Django 2.1.3 on 2018-12-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20181210_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Product')),
            ],
        ),
    ]
