# Generated by Django 2.1.3 on 2018-12-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Product',
            new_name='product',
        ),
    ]
